baseURL = 'https://well-made.uk/'
title = 'Well-made.uk'
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 12

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
  author = "Ben Wilde"
  info = "I build well-made websites."
  description = "Well-made websites by Ben Wilde"
  keywords = "blog,developer,personal"
  avatarurl = "/img/avatar-comp.jpg"

  favicon_32 = "/img/avatar-comp.jpeg"
  favicon_16 = "/img/avatar-comp.jpeg"

  since = 2019

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.min.css"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Projects"
  weight = 5
  url  = "projects/"

[[menu.main]]
  name = "Google Policy"
  weight = 10
  url  = "google-free/"

[[menu.main]]
  name = "Hire Me"
  weight = 1000
  url  = "https://app.hellobonsai.com/f/fde64b9ccf00bdb"
