baseURL = 'https://well-made.uk/'
title = 'Well-made.uk'
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
  customCSS = ["css/custom.min.css"]
  # customJS = ["js/custom.js"]

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/"

[[menu.main]]
  name = "Free"
  weight = 1
  url  = "free/"
